### ISSUE TITLE
Crashes when fritz-box is unreachable

### ISSUE THREAD

**Issue by Eggn1n3** [bashGroup/node-red-contrib-fritz#5]
Hi,
When the Fritzbox becomes unreachable or you provide the wrong IP-address node-red crashes completely:

In output  below you can see that (fritz-box) 192.168.5.2 cannot be reached and crashed node-
red.

5 Mar 19:52:00 - [red] Uncaught Exception:
5 Mar 19:52:00 - Error: connect ECONNREFUSED 192.168.5.2:1012
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

Can this exception be caught somehow?

**Comment by Eggn1n3** [comment]
Thanks Mapero, I can confirm it works great now!
